### ISSUE TITLE
Beds explode in the end.

### ISSUE THREAD

**Issue by GavJenks** [CivClassic/SimpleAdminHacks#2]
I was told this was supposed to not be happening on a server I am playing on (Civclassic test), so it is probably a bug in the code.

Also, if reinforced with citadel, beds work normally allowing spawnpoints to be set and everything.

This is probably a weird mishmash of adminhacks, citadel, randomspawn, etc. Not sure where best to put it

**Comment by Maxopoly** [comment]
> Beds explode in the end
Fixed long ago

>  if reinforced with citadel, beds work normally allowing spawnpoints to be set and everything

Neither intended to be changed, nor appropriate for this repo
