### ISSUE TITLE
Obsidian Grinder's Do not function without string reinforcement.

### ISSUE THREAD

**Issue by KaloHG** [CivClassic/SimpleAdminHacks#26]
Currently, the obsidian grinder hack does not function unless the string is reinforced. Forcing users who are attempting to bot obsidian production to /ctf [group], /ctb in order to grind obsidian. 

Please fix.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/SimpleAdminHacks/pull/27
