### ISSUE TITLE
Replace gold block tps with respawn anchors

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/SimpleAdminHacks#32]
Turn them into respawn anchors. Activate the anchor if there is a suitable destination, do a full scan whenever a respawn anchor is broken, placed or a teleport works/fails. Means there still are piston shenanigans etc. to make a anchor display the false state and trick others, but that's fine.

**Comment by wingzero54** [comment]
We've already done a few things updating gold bock elevators, may as well let this go.
