### ISSUE TITLE
Some Autload settings are loaded as wrong types

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/SimpleAdminHacks#40]
Particularly longs with a `L` suffix will be loaded as int and may not work properly.

@Protonull is working on fixing it seemingly

**Comment by Protonull** [comment]
Should be fixed with https://github.com/CivClassic/SimpleAdminHacks/pull/41/commits/0343638c61a092c8ade4a6c86bf7a2304db4e2af#diff-41d869965546c7ea2dd6a572c36c4ab81df1ae38d9fabe2adafd9a94a4e1b772R195-R211, though the problem wasn't L-suffixed values.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/CivClassic/SimpleAdminHacks/pull/41
