### ISSUE TITLE
Run command on amount of AntiFastBreak violations

### ISSUE THREAD

**Issue by Maxopoly** [CivClassic/SimpleAdminHacks#42]
It works fine now, so we can autoban

**Comment by wingzero54** [comment]
This issue is similar https://github.com/CivClassic/Kira/issues/11, the issue is antifastbreak violations can be triggered thousands of times and kira is rate limited by discord so kira spends hours posting the backlog of rate-limited fastbreak violations

**Comment by Protonull** [comment]
What is the message being spammed?

**Comment by wingzero54** [comment]
https://github.com/CivClassic/SimpleAdminHacks/blob/master/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/AntiFastBreak.java#L166
