### ISSUE TITLE
Wandering Trader trading is not actually disabled

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/SimpleAdminHacks#43]
Right clicking wandering traders is supposed to be cancelled so you can't open the trade menu, but right clicking them still works anyway and the trade menu can be accessed.

**Comment by Protonull** [comment]
Really? It's never worked for me

**Comment by wingzero54** [comment]
I just tested with two different people who were both able to open the trade menu

**Comment by Maxopoly** [comment]
Maybe config issue?

**Comment by Diet-Cola** [comment]
This would make sense cause even essence throwing is enabled and stuff for a week or two

**Comment by wingzero54** [comment]
Fixed with https://github.com/CivClassic/AnsibleSetup/commit/14f6e8ecce724f477da51049119946d59f1ba26d
